### ISSUE TITLE
I got Cannot read property 'startSession' of undefined

### ISSUE THREAD

**Issue by pathawee** [RevMob/react-native-revmob#1]
I use
"react": "~15.3.0",
"react-native": "^0.34.0",
"react-native-revmob": "^9.2.1",

I ran on android simulator (genymotion) and I got Cannot read property 'startSession' of undefined
For ios simulator nothing happen (No ads display) Seem like startSession not call

``````
RevMobManager.startSession(this.ads_app_id, function revMobStartSessionCb(err){
        if(!err) RevMobManager.loadCustomBanner(0, 200, 100, 200); // Load custom banner if session starts successfully.
      })```
``````

**Comment by thiagomurakami** [comment]
Solution on [RevMob's forum thread](https://forum.revmobmobileadnetwork.com/topic/424/i-got-cannot-read-property-startsession-of-undefined)
