### ISSUE TITLE
Rewarded video not working

### ISSUE THREAD

**Issue by RatFou** [RevMob/react-native-revmob#2]
Hi,

I'm using the sampleApp on Android, in live mode (APP ID is OK). I haven't changed anything in the code.

I can start a session and load rewarded video (onRevmobRewardedVideoDidLoad) but I've got nothing when I click on "Show Rewarded Video". Could you please explain to me what is the problem?

Thanks

**Comment by thiagomurakami** [comment]
Sure, I'd be glad to help.

What version of RN are you using? Were you building on Android or iOS device/simulator?

**Comment by RatFou** [comment]
Thanks, I'm using the last version of RN (0.35). I'm building on Android (simulator and device).

**Comment by RatFou** [comment]
Hi @thiagomurakami did you manage to run the rewarded video on Android device/emulator?

**Comment by thiagomurakami** [comment]
Yes, on a Galaxy S5 (Android 6.0.1), I can show test ads just fine!

Do you have any logs of what is happening? Android logs would be nice, because our native Android SDK usually logs useful info.

**Comment by RatFou** [comment]
My bad, I read the official documentation and it is said that I have to change AndroidManifest to open Rewarded videos.

Maybe you should add "If you wish to use fullscreen, video, or rewarded video ads" in the Github readme ;)

Thanks for your help!

**Comment by thiagomurakami** [comment]
Oh I see, you forgot to add the Activity to the AndroidManifest.

Sure, that's a great suggestion, will do it soon, thanks!

**Comment by RatFou** [comment]
Absolutely :)
