### ISSUE TITLE
Does not work on Android

### ISSUE THREAD

**Issue by 7kfpun** [RevMob/react-native-revmob#4]
react-native: 0.41.2

**Comment by thiagomurakami** [comment]
Will take a look at it 👍

**Comment by thiagomurakami** [comment]
Hi @7kfpun, just built a quick app here and installed ```react-native-revmob``` here and everything seems to be working fine on Android. Are you running on a device or simulator? Are all ad units broken?

It'd really help if you could attach logcat logs with:
```
adb logcat | grep RevMob
```

Thanks
